substitutions:
  _TAG: "1.0.0"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/flask-helloworld:${_TAG}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/flask-helloworld:${_TAG}']

images:
- 'us.gcr.io/flask-helloworld:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY

