steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flask-helloworld:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flask-helloworld:$COMMIT_SHA']
images:
- 'gcr.io/flask-helloworld:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY