steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/flask-helloworld:$TAG', '.']
  env:
  - 'TAG=1.0.0'
- name: 'us.gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/flask-helloworld:$COMMIT_SHA']
images:
- 'gcr.io/flask-helloworld:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
